---
platform: linux
image: docker:///cloudfoundry/cli-ci

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  PUBLISH_TO_S3_DIR:

inputs:
- name: cli
- name: cf-cli-binaries

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    root=$PWD

    mkdir archives

    filename_regex="cf-cli([-_0-9a-z]+)?(\.[a-z]+)?"

    echo "Creating edge binary archives"

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz

      for BIN in cf-cli_[lo]*; do # linux, osx
        [[ "${BIN}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"

        cp ${BIN} cf
        tar cvzf $root/archives/cf-cli_edge${os_arch}.tgz cf
        rm cf
      done

      for BIN in cf-cli_win*; do
        [[ "${BIN}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"

        cp ${BIN} cf.exe
        zip $root/archives/cf-cli_edge${os_arch}.zip cf.exe
        rm cf.exe
      done
    popd

    echo "Uploading edge binary archives"

    pushd archives
      for archive in *; do
        aws s3 cp $archive s3://${PUBLISH_TO_S3_DIR}/$archive
      done
    popd
